### ISSUE TITLE
"error: failed to parse manifest"

### ISSUE THREAD

**Issue by bortzmeyer** [bgpkit/ris-live-rs#2]
```
% cargo install ris-live-rs   
    Updating crates.io index
  Downloaded ris-live-rs v0.1.0
error: failed to parse manifest at `/home/stephane/.cargo/registry/src/github.com-1ecc6299db9ec823/ris-live-rs-0.1.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

My knowledge of Rust is limited so I cannot really help to solve the problem.

**Comment by digizeph** [comment]
@bortzmeyer thanks for your issue report!

The minimum Rust version for this crate is Rust 1.56, which introduces the 2021 edition flag. I am planing to reduce the minimum required Rust version soon, so that older Rust can build as well.

In the mean time, if you could upgrade your Rust version, then it would be great if you do so and give it a try again.

**Comment by bortzmeyer** [comment]
OK, with `rustc 1.56.0`, it works, thanks.

**Comment by digizeph** [comment]
The [release of version 0.1.1](https://github.com/bgpkit/ris-live-rs/releases/tag/v.0.1.1) brings down the minimum support rust version to 1.46, so you should also be able to build/run with older rust version now.
